### ISSUE TITLE
TypeLoad exception thrown in v1.0.0.3

### ISSUE THREAD

**Issue by kn327** [cnblogs/ServiceStackRedisCache#2]
Hello,

When attempting to use the latest nuget package available (1.0.0.3), my application results in the following exception:

It appears as if one of the interfaces does not implement the GetAsync method.

```
Unhandled exception. System.TypeLoadException: Method 'GetAsync' in type 'Microsoft.Extensions.Caching.ServiceStackRedis.ServiceStackRedisCache' from assembly 'ServiceStackRedisCache, Version=1.0.0.3, Culture=neutral, PublicKeyToken=null' does not have an implementation.
   at Microsoft.Extensions.DependencyInjection.RedisCacheServiceCollectionExtensions.AddDistributedServiceStackRedisCache(IServiceCollection services, Action`1 setupAction)
   at my_project.Program.<>c.<CreateHostBuilder>b__1_3(HostBuilderContext hostContext, IServiceCollection services) in C:\Projects\my_project\my_project\Program.cs:line 46
   at Microsoft.Extensions.Hosting.HostBuilder.CreateServiceProvider()
   at Microsoft.Extensions.Hosting.HostBuilder.Build()
   at my_project.Program.Main(String[] args) in C:\Projects\my_project\my_project\Program.cs:line 16
```

**Comment by kn327** [comment]
Looks like the issue was that the link provided in the ReadMe pointed to an older version.

Bad Package (from ReadMe link): https://www.nuget.org/packages/ServiceStackRedisCache

Latest version can be found here: https://www.nuget.org/packages/Microsoft.Extensions.Caching.ServiceStackRedis/
